# Generated by Django 3.2.25 on 2024-09-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240914_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='direction',
            new_name='directions',
        ),
    ]
